config/routes.rb
Shop::Application.routes.draw do
  get "administrator/index"

  get "administrator/show"

  devise_for :admins

  devise_for :users

  root :to => "home#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # Setup accessible (or protected) attributes for your model
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  belongs_to :item
  has_many :item_categories
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

  has_many :purchases
  has_many :users, through: :purchases
  has_many :categories
  has_many :item_categories
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  attr_accessible :category_id, :item_id
  belongs_to :categories
  belongs_to :items
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  attr_accessible :user_id, :item_id

  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :admin
  # attr_accessible :title, :body

  has_many :purchases
  has_many :items, through: :purchases


end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = User.joins(:purchases).group("users.id")
  end

  def show
    @user = User.find(params[:user])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? && current_user.admin?
      redirect_to administrator_index_path
    end
  end
end

app/helpers/administrator_helper.rb
module AdministratorHelper
  def find_item(user)
    Item.joins(:purchases).where(:purchases => {:user_id => user.id})
  end
  def find_categories(item)
    Category.joins(:item_categories).where(:item_categories => {:item_id => item.id})
  end
  def find_recommend(category)
    @recommend = []
    category.each do |i|
      @recommend = @recommend + Item.joins(:item_categories).where(:item_categories => {:category_id => i.id})
    end
    @recommend.uniq!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/administrator/index.html.erb
<table border="1">
  <thead>
    <tr>
      <th>User Name</th>
      <th>Items Purchased</th>
      <th>Categories</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @user.each do |u| %>
      <td>
        <%=link_to u.name, administrator_show_path(:user => u)  %>
      </td>
      <td>
        <% items = find_item(u) %>
        <%= items.map {|item| item.name}.to_sentence %>
      </td>
      <td>
        <% category = [] %>
        <% items.each do |i| %>
          <% category = (category + find_categories(i)).uniq %>
        <% end %>
        <%= category.map {|categories| categories.name}.to_sentence %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/administrator/show.html.erb
<h1><%= @user.name %></h1>
<table border="1">
  <thead>
  <tr>
    <th>Items Purchased</th>
    <th>Categories</th>
  </tr>
  </thead>
  <tbody>
  <tr>
        <td>
          <% items = find_item(@user) %>
          <%= items.map {|item| item.name}.to_sentence %>
        </td>
        <td>
          <% category = [] %>
          <% items.each do |i| %>
              <% category = (category + find_categories(i)).uniq %>
          <% end %>
          <%= category.map {|categories| categories.name}.to_sentence %>
        </td>
        </tr>
    </tbody>
</table>
<h1>Recommended Items</h1>

<% find_recommend(category) %>

<%= (@recommend-items).map {|item| item.name}.to_sentence %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="user_nav">
  <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>


<%= yield %>

</body>
</html>